### ISSUE TITLE
コーディング規約が欲しい

### ISSUE THREAD

**Issue by treby** [miyukki/ApplestFramework#16]
既に結構カオスな気がしたので、何かあると助かります。
- ハードタブ／ソフトタブか？
  - ハードタブかと思いきや、ファイルによって混在あり。
- { の前に改行を入れるかどうか：多少のぶれがみられる
  - if文 / while文 / for文など
  - class / functionなど

あったらContributeしやすくなる気がしました。

**Comment by miyukki** [comment]
基本的にハードタブを使用しておりました。

最近は{の前に改行を入れるようにしたのでそのせいだと思います<ぶれ。

何かしらのコーディング規則を近日中に制定する予定です。

**Comment by treby** [comment]
期待してます！
ググってるとは思いますが、既存のを使うのも一つの手ですねー。

http://qiita.com/hshimo/items/04be1f432240c58300f4

まあこの指摘自体、なんか職業病(になってしまった……)みたいなものですが一つ。
いちゃもんつけてるわけじゃないよ＞＜

**Comment by miyukki** [comment]
そうですねーCake PHPあたりの規則に従う予定です。

なので現在書いている

``` php
if ($hoge)
{
    //todo
}
else
{
    //todo
}
```

という書き方は間違いになります。

(いやいやいいんですよ、Issues投げてくれるだけで喜ぶMなので)
